version: '3.1'
services:
  odoo:
    image: odoo:16.0
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./project:/mnt/project
    command: odoo
    #command: pip3 install -r /mnt/project/requirements.txt
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo 
